version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bobobed-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_DB: bobobed_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # app:
  #   build: .
  #   container_name: bobobed-backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: mypassword123
  #     DB_NAME: bobobed_db
  #   depends_on:
  #     - db

volumes:
  pgdata:
